In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("EasyVisa.csv")
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [4]:
data = df.to_dict(orient='records')
data[:5]

[{'case_id': 'EZYV01',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 14513,
  'yr_of_estab': 2007,
  'region_of_employment': 'West',
  'prevailing_wage': 592.2029,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV02',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2412,
  'yr_of_estab': 2002,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 83425.65,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV03',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 44444,
  'yr_of_estab': 2008,
  'region_of_employment': 'West',
  'prevailing_wage': 122996.86,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV04',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 98,
  'yr_of_estab': 1897,
  'region_of_employment': 'West',
  'prevailing_wage': 83434.03,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV05',
  'continent': 'Africa',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1082,
  'yr_of_estab': 2005,
  'region_of_employment': 'South',
  'prevailing_wage': 149907.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'}]

In [5]:
len(data)

25480

In [20]:
import os
from dotenv import load_dotenv

load_dotenv()

True

In [21]:
DB_NAME = os.getenv("DB_NAME")
COLLECTION_NAME = os.getenv("COLLECTION_NAME")
CONNECTION_URL = os.getenv("CONNECTION_URL")

In [8]:
import pymongo

In [ ]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

rec = collection.insert_many(data)

In [23]:
records = collection.find()

In [24]:
records

In [25]:
for i, j in enumerate(records):
    print(f"{i}:  {j}")
    if i>4: break

0:  {'_id': ObjectId('6a538c80cf87c0cdf9ee4446'), 'case_id': 'EZYV01', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 14513, 'yr_of_estab': 2007, 'region_of_employment': 'West', 'prevailing_wage': 592.2029, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
1:  {'_id': ObjectId('6a538c80cf87c0cdf9ee4447'), 'case_id': 'EZYV02', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2412, 'yr_of_estab': 2002, 'region_of_employment': 'Northeast', 'prevailing_wage': 83425.65, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
2:  {'_id': ObjectId('6a538c80cf87c0cdf9ee4448'), 'case_id': 'EZYV03', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 44444, 'yr_of_estab': 2008, 'region_of_employment': 'West', 'prevailing_wage': 122996.86, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
3:  {'_id': ObjectId('6a538c80cf87c0cdf9ee4449'), 'case_id': 'EZYV04', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 98, 'yr_of_estab': 1897, 'region_of_employment': 'West', 'prevailing_wage': 83434.03, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
4:  {'_id': ObjectId('6a538c80cf87c0cdf9ee444a'), 'case_id': 'EZYV05', 'continent': 'Africa', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1082, 'yr_of_estab': 2005, 'region_of_employment': 'South', 'prevailing_wage': 149907.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
5:  {'_id': ObjectId('6a538c80cf87c0cdf9ee444b'), 'case_id': 'EZYV06', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2339, 'yr_of_estab': 2012, 'region_of_employment': 'South', 'prevailing_wage': 78252.14, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}

In [15]:
df = pd.DataFrame(list(records))
df.head()

,_id,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,6a538c80cf87c0cdf9ee4453,EZYV14,Asia,Bachelor's,Y,N,1652,2007,Midwest,107196.03,Year,Y,Certified
1,6a538c80cf87c0cdf9ee4454,EZYV15,Asia,Master's,Y,Y,15756,2006,South,220081.73,Year,Y,Certified
2,6a538c80cf87c0cdf9ee4455,EZYV16,Asia,High School,Y,N,4897,1987,West,74108.02,Year,Y,Denied
3,6a538c80cf87c0cdf9ee4456,EZYV17,Europe,Master's,Y,N,76638,1991,Midwest,3706.79,Year,Y,Certified
4,6a538c80cf87c0cdf9ee4457,EZYV18,Asia,Master's,Y,N,2747,2001,West,16132.61,Year,Y,Certified

In [18]:
if "_id" in df.columns.to_list():
    df = df.drop(columns=["_id"])

In [19]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV14,Asia,Bachelor's,Y,N,1652,2007,Midwest,107196.03,Year,Y,Certified
1,EZYV15,Asia,Master's,Y,Y,15756,2006,South,220081.73,Year,Y,Certified
2,EZYV16,Asia,High School,Y,N,4897,1987,West,74108.02,Year,Y,Denied
3,EZYV17,Europe,Master's,Y,N,76638,1991,Midwest,3706.79,Year,Y,Certified
4,EZYV18,Asia,Master's,Y,N,2747,2001,West,16132.61,Year,Y,Certified